### ISSUE TITLE
Email spam coming from this repo

### ISSUE THREAD

**Issue by BKirev** [glossopoeia/boba#74]
Hello,

It's the first time I hear about **glossopoeia/boba** and it wasn't nice at all. I never starred, forked and/or participated in any other way in this repo. Nevertheless, I've got a spam email with the following content:

![image](https://user-images.githubusercontent.com/6042641/209940294-0792515a-748f-4b91-8c30-d5a9150f1cdf.png)

I hope it wasn't intentional.

**Comment by robertkleffner** [comment]
Hi @BKirev, I can assure you that no one associated with this repo was involved in this spam account. I myself was at-ed with a similar message in the discussions of a someone else's repo, and reported the spamming account. I'm looking into ways to prevent this sort of thing from being done from the Boba repository in the future, but it may be a Github issue and the only way to fully prevent it may be to remove the discussions feature from this repository, which isn't that exciting a prospect.

My hope is that you did not report this repository or its owner, but did report the account the sent the spam message. Most likely its only purpose is to send such messages.

**Comment by BKirev** [comment]
No, I haven't reported the repo or the owner. I wanted to report it here first, because it looked like it's something shady that's not coming from the repo itself anyway.
Hopefully Github will be able to do something about this.
